### ISSUE TITLE
Possibile modifica

### ISSUE THREAD

**Issue by ghost** [federinik33/Amazon-price-monitor#2]
Ottimo script, sarebbe possibile una modifica per inserire più URLs da un file senza fare a mano ogni volta?
E' obbligatorio inserire il prezzo desiderato o semplicemente se non inserisco niente può monitorare qualsiasi drop di prezzo?
Ho in mente una bella idea dove potremmo guadagnarci entrambi.
Se ti interessa questo è il mio Telegram: @Gabar_18

**Comment by federinik33** [comment]
Ciao, grazie, le due modifiche sono certamente possibili e fattibili, non ho telegram, ma se vuoi puoi contattarmi all'indirizzo mail federinik33@gmail.com
